version: '4.29.0'

services:
  frontend:
    build:
      context: ./w2_front
    ports:
      - "3000:80"
    depends_on:
      - backend

  backend:
    build:
      context: ./w2parser
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=sqlite:///app/W2_data.db
